api/urls.py
from django.urls import path, include
from django.views import View
from rest_framework.routers import DefaultRouter

from .views import (
    BookingViewSet, CategoriesViewSet, ChangePasswordView, CheckOTPView, FavouritesViewSet,
    GuestViewSet, HotelAvailabilityViewSet, HotelPaymentMethodViewSet, HotelReviewViewSet, HotelsViewSet,
    LoginView, LogoutView, NotificationsViewSet, PaymentViewSet, RegisterView, RoomReviewViewSet, SendSMSView,
    UserProfileView, call_gemini_chat_bot, get_best_hotels_by_gemini, usage
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

app_name = 'api'
# Test
router = DefaultRouter()
router.register(r'hotels', HotelsViewSet, basename='hotels')
router.register(r'favourites', FavouritesViewSet, basename='favourite')
router.register(r'hotel-payment-methods', HotelPaymentMethodViewSet, basename='hotel-payment-methods')
router.register(r'payment', PaymentViewSet, basename='payment')
router.register(r'bookings', BookingViewSet,basename='booking')
router.register(r'notifications', NotificationsViewSet,basename='notification')
router.register(r'categories', CategoriesViewSet,basename='categories')
router.register(r'guests', GuestViewSet, basename='guest')
router.register(r'RoomReview', RoomReviewViewSet, basename='review')
router.register(r'hotel-reviews', HotelReviewViewSet, basename='hotel-review')

# router.register(r'user-profile', UserProfileView,basename='user-profile')
# router.register(r'hotel_availability', HotelAvailabilityViewSet,basename='hotel_availability')


urlpatterns = [

    path('', include(router.urls)),





    path('hotel_availability/', HotelAvailabilityViewSet.as_view(), name='hotel_availability'),
    path('user-profile/', UserProfileView.as_view(), name='user-profile'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    # path('profile/', UserProfileView.as_view(), name='user-profile'),
    #  JWT Token endpoints
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    #  JWT authentication endpoints
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('usage/', usage, name='usage'),
    path('chat-assistant/', call_gemini_chat_bot, name='chat_assistant'),
    path('get_best_hotels_by_gemini/', get_best_hotels_by_gemini, name='get_best_hotels_by_gemini'),
    path('create-guest/', GuestViewSet.as_view({'post': 'create'}), name='create-guest'),
    path('create-multiple-guests/', GuestViewSet.as_view({'post': 'create_multiple'}), name='create-multiple-guests'),
    path('check-otp/', CheckOTPView.as_view(), name='check_otp'),
    path('send-sms/', SendSMSView.as_view(), name='send_sms'),
]





# http://127.0.0.1:8000/api/hotels/search?room_number=201&check_in=2025-06-11&check_out=2025-06-12&adult_number=1&hotel_name=$$$&location=###&category_type=@@@

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.user_dashboard_index, name='user_dashboard_index'),
    path('user-dashboard/bookings', views.user_dashboard_bookings, name='user_dashboard_bookings'),
    path('cancel/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    
    # تعديل المسار settings ليكون مميزًا
    path('user-dashboard/settings/email', views.user_dashboard_settings_email, name='user_dashboard_settings_email'),
    path('user-dashboard/settings/password', views.user_dashboard_settings_password, name='user_dashboard_settings_password'),
    path('user-dashboard/settings', views.user_dashboard_settings, name='user_dashboard_settings'),
    path('user-dashboard/settings/profile', views.user_profile_dashboard_settings, name='user_profile_dashboard_settings'),
    
    path('user-dashboard/wishlist', views.user_dashboard_wishlist, name='user_dashboard_wishlist'),
    path('user-add-to-wishlist', views.add_to_favorites, name='add_to_favorites'),
    path('user-dashboard/reviews', views.user_dashboard_reviews, name='user_dashboard_reviews'),
    path('user-dashboard/profile', views.user_dashboard_profile, name='user_dashboard_profile'),
    
    # المسار الخاص بحذف المفضلة
    path('remove_favourite/<int:favourite_id>/', views.remove_favourite, name='remove_favourite'),
    path('cancel-payment/<int:payment_id>/', views.cancel_payment, name='cancel_payment'),

    path('notifications/mark-all-as-read/', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('user-dashboard/booking/<int:booking_id>/detail/', views.user_booking_detail, name='user_booking_detail'),
    path('guest/<int:guest_id>/delete/', views.delete_guest, name='delete_guest'),

]

home/urls.py
from django.urls import path,include
from . import views


app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('price/',views.price,name='price'),
    path('contact/',views.contact,name='contact'),
    path('hotels',views.hotels,name='hotels'),
    path('privacy-policy',views.privacy_policy,name='privacy_policy'),
    path('payment-policy',views.payment_policy,name='payment_policy'),
    path('terms-condition',views.terms_condition,name='terms_condition'),
    path('hotel/<slug:slug>/', views.hotel_detail, name='hotel_detail'),
    # Rooms
    path('contact/thank-you/', views.thank_you, name='thank_you'),
    path('pricing/', views.pricing, name='pricing'),
    path('room-search-result', views.room_search_result, name='room-search-result'),
    path('rooms', views.room_list, name='room_list'),
    
    ]

hotels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from api.admin import admin_site

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin_site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('HotelManagement/', include('HotelManagement.urls', namespace='HotelManagement')),
    path('', include('home.urls'), name='home'),
    path('rooms/', include('rooms.urls')),
    path('bookings/', include('bookings.urls', namespace='bookings')),
    path('payments/', include('payments.urls')),
    path('reviews/', include('reviews.urls')),
    path('services/', include('services.urls', namespace='services')),
    path('blog/', include('blog.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('customer/', include('customer.urls')),

    path('notifications/', include('notifications.urls',namespace='notifications')),
    
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path # type: ignore #
from .views import notifications_view, mark_notifications_read, mark_notification_read, handle_notification, all_notifications

app_name = 'notifications'

urlpatterns = [
    path('notifications/', notifications_view, name='notifications'),
    path('all_notifications/<int:user_id>/', all_notifications, name='all_notifications'),
    path('all_notifications/', lambda request: all_notifications(request, request.user.id), name='all_notifications_current_user'),
    path('notifications/read/', mark_notifications_read, name='mark_notifications_read'),
    path('mark_read/<int:notification_id>/', mark_notification_read, name='mark_notification_read'),
    path('notifications/<int:notification_id>/', handle_notification, name='handle_notification'),
]

payments/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required
from payments.services.reports import revenue_summary_view, export_revenue_summary_pdf

app_name = 'payments'
urlpatterns = [
    # Payment methods for Hotels
    path('checkout/<int:room_id>/', views.checkout, name='checkout'),
    path('process_booking/<int:room_id>/', views.process_booking, name='process_booking'),
    path("save-guests/<int:room_id>/", views.save_guests, name="save_guests"),
    path('confirm-payment/', views.hotel_confirm_payment, name='hotel_confirm_payment'),
#    path('process-hotel-payment/', views.process_hotel_payment, name='process_hotel_payment'),
#    path('payment_complete/<int:hotel_id>/', views.payment_complete, name='payment_complete'),

    path('add_guest/<int:booking_id>/', views.add_guest, name='add_guest'),
    path('payment-detail/<int:pk>/', views.payment_detail_view, name='external-payment-detail'),
    
    # Report URLs
    path('reports/revenue-summary/', staff_member_required(revenue_summary_view), name='revenue-summary'),
    path('reports/revenue-summary/export-pdf/', staff_member_required(export_revenue_summary_pdf), name='revenue-summary-export-pdf'),
    path('payments/<int:payment_id>/change-status/', views.change_payment_status_view, name='change_payment_status'),
]

templates/frontend/layout/footer.html
{% load static %}

<section
class="footer-area section-bg padding-top-40px padding-bottom-30px"
>
<div class="container">
  <div class="row align-items-center">
    <div class="col-lg-8">
      <div class="term-box footer-item">
        <ul class="list-items list--items d-flex align-items-center">
          <li><a href="#">البنود و الظروف</a></li>
          <li><a href="#">سياسة خاصة</a></li>
          <li><a href="#">مركز المساعدة</a></li>
        </ul>
      </div>
    </div>
    <!-- end col-lg-8 -->
    {% if socialMediaLink %}
    <div class="col-lg-4">

      <div class="footer-social-box text-end">
        <ul class="social-profile">
          {% for socialMediaLink in socialMediaLink %}
          <li>
            <a href="{{socialMediaLink.link}}"><i class="{{socialMediaLink.icon}}"></i></a>
          </li>
          {% endfor %}
         
        </ul>
      </div>
    </div>
    <!-- end col-lg-4 -->
    {% endif %}
  </div>
  <!-- end row -->
</div>
<div class="section-block mt-4 mb-5"></div>
<div class="container">
  <div class="row">
    <div class="col-lg-3 responsive-column">
      <div class="footer-item">
        <div class="footer-logo padding-bottom-30px">
          <a href="index.html" class="foot__logo"
            ><img src="{{setting.footer_logo.url}}" alt="logo"
          /></a>
        </div>
        <!-- end logo -->
        <p class="footer__desc">
          {{setting.description}}
        </p>
        <ul class="list-items pt-3">
          <li>{{setting.address}}</li>
          <li>{{setting.phone_number}}</li>
          <li><a href="#">{{setting.email}}</a></li>
        </ul>
      </div>
      <!-- end footer-item -->
    </div>
    <!-- end col-lg-3 -->
    <div class="col-lg-3 responsive-column">
      <div class="footer-item">
        <h4
          class="title curve-shape pb-3 margin-bottom-20px"
          data-text="curvs"
        >
          وصول اسرع
        </h4>
        <ul class="list-items list--items">
          <li><a href="/about">معلومات عنا</a></li>
          <li><a href="/services">خدمات</a></li>
          <li><a href="/blog">أخبار</a></li>
          <li><a href="/contact">الدعم</a></li>
        </ul>
      </div>
      <!-- end footer-item -->
    </div>
  
    <!-- end col-lg-3 -->
    <div class="col-lg-3 responsive-column">
      <div class="footer-item">
        <h4
          class="title curve-shape pb-3 margin-bottom-20px"
          data-text="curvs"
        >
          طرق الدفع
        </h4>
        <p class="footer__desc pb-3">
          ادفع بأي طريقة تختارها ، نحن ندعم جميع خيارات الدفع.
        </p>
        <img src="images/payment-img.png" alt="" />
      </div>
      <!-- end footer-item -->
    </div>
    <!-- end col-lg-3 -->
  </div>
  <!-- end row -->
  <div class="section-block"></div>
  <div class="row">
    <div class="col-lg-12">
      <div class="copy-right padding-top-30px">
        <p class="copy__desc">
          &copy; Copyright TeamSoft 2025. Made with
          <span class="la la-heart"></span> by
          <a href="https://ahmed-div.netlify.app"
            >TeamSoft</a
          >
        </p>
      </div>
      <!-- end copy-right -->
    </div>
    <!-- end col-lg-12 -->
  </div>
  <!-- end row -->
</div>
<!-- end container -->
</section>

templates/frontend/layout/menu.html
{% load menu_generator %}
{% load static %}

<header class="header-area">
  <div class="header-top-bar padding-right-100px padding-left-100px">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="header-top-content">
            <div class="header-left">
              <ul class="list-items">
                <li>
                  <a href="#"><i class="la la-phone me-1"></i>{{setting.phone_number}}</a>
                </li>
              
                <li>
                  <a href="#"><i class="la la-envelope me-1"></i>{{setting.email}}</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="header-top-content">
            <div class="header-right d-flex align-items-center justify-content-end gap-3">
              <div class="header-right-action">
                <h6>{{setting.default_language}}</h6>
              </div>
              <div class="header-right-action">
                <h6>{{setting.default_currency}}</h6>
              </div>
              <!-- Notifications -->
              <div class="header-right-action position-relative">
                <li class="nav-item dropdown noti-nav list-unstyled">
                  <a href="#" class="nav-link p-0 position-relative" data-bs-toggle="dropdown" aria-expanded="false" id="notification-button">
                    <i class="fa-solid fa-bell fs-5"></i>
                    {% if unread_notifications_count > 0 %}
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="notification-count">
                      {{ unread_notifications_count }}
                    </span>
                    {% endif %}
                  </a>
                  <div class="dropdown-menu dropdown-reveal dropdown-menu-xl dropdown-menu-end mt-2">
                    <div class="dropdown-header drop-reveal-header">
                      <h6 class="title">
                        لديك <strong class="text-black">{{ unread_notifications_count }}</strong> إشعارات غير مقروءة
                      </h6>
                    </div>
                    <div class="list-group drop-reveal-list" id="notification-list">
                      {% for notification in notifications %}
                        {% if notification.status == '0' %}
                        <a href="{% url 'notifications:handle_notification' notification.id %}" class="list-group-item list-group-item-action unread" data-id="{{ notification.id }}">
                          <div class="msg-body d-flex align-items-center">
                            <div class="icon-element flex-shrink-0 me-3 ms-0">
                              <i class="la la-bell"></i>
                            </div>
                            <div class="msg-content w-100">
                              <h3 class="title pb-1">{{ notification.message }}</h3>
                              <p class="msg-text">من: {{ notification.sender.get_full_name }}</p>
                              <p class="msg-text">{{ notification.send_time|timesince }} مضت</p>
                              <p class="msg-type">
                                {% if notification.notification_type == '0' %}
                                  <span class="badge bg-info">معلومة</span>
                                {% elif notification.notification_type == '1' %}
                                  <span class="badge bg-warning">تحذير</span>
                                {% elif notification.notification_type == '2' %}
                                  <span class="badge bg-success">نجاح</span>
                                {% elif notification.notification_type == '3' %}
                                  <span class="badge bg-danger">خطأ</span>
                                {% endif %}
                              </p>
                            </div>
                          </div>
                        </a>
                        {% endif %}
                      {% endfor %}
                    </div>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'notifications:all_notifications' user.id %}" class="dropdown-item drop-reveal-btn text-center">مشاهدة الكل</a>
                    {% endif %}
                  </div>
                </li>
              </div>
              <!-- /Notifications -->
              {% comment %} <a href="{% url 'payments:add_guest' 1 %}" class="">add guest</a> {% endcomment %}
              {% if request.user.is_authenticated %}
              <div class="header-right-action">
                <div class="dropdown">
                  <button class="theme-btn theme-btn-small dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="la la-user me-1"></i> {{ request.user.username }}
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="userDropdown">
                    {% if request.user.is_customer %}
                    <li><a class="dropdown-item" href="{% url 'customer:user_dashboard_index' %}"><i class="la la-user-circle me-2"></i>الملف الشخصي</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:user_dashboard_bookings' %}"><i class="la la-hotel me-2"></i>حجوزاتي</a></li>
                    {% endif %}
                    {% if request.user.is_staff %}
                    <li><a class="dropdown-item" href="{% url 'admin:index' %}"><i class="la la-cog me-2"></i>لوحة التحكم</a></li>
                    {% endif %}
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item text-danger" href="{% url 'users:logout' %}"><i class="la la-sign-out me-2"></i>تسجيل خروج</a></li>
                   
                  </ul>
                </div>
              </div>
              {% else %}
              <div class="header-right-action">
                  {% comment %} <a href="#" class="theme-btn theme-btn-small theme-btn-transparent me-1" data-bs-toggle="modal" data-bs-target="#signupPopupForm">سجل</a> {% endcomment %}
                <a href="{% url 'users:register' %}" class="theme-btn theme-btn-small theme-btn-transparent me-1">سجل</a>
                <a href="{% url 'users:login' %}" class="theme-btn theme-btn-small">تسجيل الدخول</a>
                  {% comment %} <a href="#" class="theme-btn theme-btn-small" data-bs-toggle="modal" data-bs-target="#loginPopupForm">تسجيل الدخول</a> {% endcomment %}
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="header-menu-wrapper padding-right-100px padding-left-100px">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="menu-wrapper justify-content-between">
            <a href="#" class="down-button"><i class="la la-angle-down"></i></a>
            <div class="logo">
              <a href="{% url 'home:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo" /></a>
              <div class="menu-toggler">
                <i class="la la-bars"></i>
                <i class="la la-times"></i>
              </div>
            </div>
            
            <div class="main-menu-content pe-0 ms-0">
              <nav class="d-flex justify-content-center">
                {% get_menu "NAV_MENU_TOP" as top_menu %}
                <ul class="d-flex justify-content-center gap-4">
                  {% for item in top_menu %}
                  <li>
                    <a href="{{ item.url }}" class="px-2">
                      {{ item.name }}
                      {% if item.submenu %}<i class="la la-angle-down"></i>{% endif %}
                    </a>
                    {% if item.submenu %}
                    <ul class="dropdown-menu-item">
                      {% for menu in item.submenu %}
                      <li><a href="{{ menu.url }}">{{ menu.name }}</a></li>
                      {% endfor %}
                    </ul>
                    {% endif %}
                  </li>
                  {% endfor %}
                </ul>
              </nav>
              {% if not request.user.is_authenticated %}
              <div class="nav-btn">
                <a href="{% url 'HotelManagement:add_request' %}" class="theme-btn theme-btn-small">أضف فندقك الآن</a>
              </div>
              {% endif %}
            </div>
            

          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var notificationButton = document.getElementById("notification-button");
    var notificationList = document.getElementById("notification-list");
    var notificationBadge = document.getElementById("notification-count");

    notificationButton.addEventListener("click", function () {
        // Toggle the display of the notification list
        notificationList.style.display = (notificationList.style.display === "block") ? "none" : "block";
    });

    // إضافة حدث للنقر على كل إشعار
    notificationList.addEventListener("click", function (event) {
      if (event.target.closest("a")) {
        var notificationItem = event.target.closest("a");
        fetch("{% url 'notifications:mark_notifications_read' %}", {
          method: "POST",
          headers: {
            "X-CSRFToken": "{{ csrf_token }}",
            "Content-Type": "application/json"
          },
          body: JSON.stringify({ notification_id: notificationItem.dataset.id })
        })
        .then(response => response.json())
        .then(data => {
          if (data.success) {
            notificationItem.remove();
            var count = parseInt(notificationBadge.textContent) - 1;
            notificationBadge.textContent = count > 0 ? count : '';
          }
        });
      }
    });
  });
</script>